[package]
name = "rust_rewrite2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
rand_xorshift = "0.3.0"
serde_json = "1.0.93"
